version: "3"

services:
  app:
    image: node:18
    tty: true
    stdin_open: true
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
